services:
  app:
    build:
      context: .
      target: development
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./quasar.config.ts:/app/quasar.config.ts
      - ./eslint.config.js:/app/eslint.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./vitest.config.ts:/app/vitest.config.ts
